/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/model.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="blockbench_export">
        <group>
          <group name="SaturnObriter" position={[0, 3.34, 0]}>
            <group name="ControlModule" position={[0, 3.64, -0.17]}>
              <mesh
                name="Navigation_module"
                castShadow
                receiveShadow
                geometry={nodes.Navigation_module.geometry}
                material={nodes.Navigation_module.material}
                position={[0, 0.45, 0.17]}
              />
              <mesh
                name="Kapton_MLI_padding"
                castShadow
                receiveShadow
                geometry={nodes.Kapton_MLI_padding.geometry}
                material={nodes.Kapton_MLI_padding.material}
                position={[0, -0.61, 0.17]}
              />
              <mesh
                name="Observation_window_part_1"
                castShadow
                receiveShadow
                geometry={nodes.Observation_window_part_1.geometry}
                material={nodes.Observation_window_part_1.material}
                position={[0, 0.28, -0.26]}
                rotation={[-0.92, 0, 0]}
              />
              <mesh
                name="Observation_window_part_2"
                castShadow
                receiveShadow
                geometry={nodes.Observation_window_part_2.geometry}
                material={nodes.Observation_window_part_2.material}
                position={[0, 0.27, -0.24]}
                rotation={[-0.92, 0, 0]}
              />
              <mesh
                name="Main_control_module"
                castShadow
                receiveShadow
                geometry={nodes.Main_control_module.geometry}
                material={nodes.Main_control_module.material}
                position={[0, -0.39, 0.17]}
                rotation={[0, 0, -Math.PI]}
              />
            </group>
            <group name="Tunnel2" position={[0, 2.19, 0]}>
              <group name="RCSthrusterbase1_3">
                <mesh
                  name="RCS_thruster_base_#1-3"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_base_#1-3"].geometry}
                  material={nodes["RCS_thruster_base_#1-3"].material}
                />
                <mesh
                  name="RCS_thruster_#1,_cone_#1"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#1,_cone_#1"].geometry}
                  material={nodes["RCS_thruster_#1,_cone_#1"].material}
                  position={[-0.41, 0.13, 0]}
                />
                <mesh
                  name="RCS_thruster_#1,_cone_#2"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#1,_cone_#2"].geometry}
                  material={nodes["RCS_thruster_#1,_cone_#2"].material}
                  position={[-0.41, -0.12, 0]}
                  rotation={[0, 0, -Math.PI]}
                />
                <mesh
                  name="RCS_thruster_#3,_cone_#1"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#3,_cone_#1"].geometry}
                  material={nodes["RCS_thruster_#3,_cone_#1"].material}
                  position={[0.41, 0.13, 0]}
                />
                <mesh
                  name="RCS_thruster_#3,_cone_#2"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#3,_cone_#2"].geometry}
                  material={nodes["RCS_thruster_#3,_cone_#2"].material}
                  position={[0.41, -0.12, 0]}
                  rotation={[0, 0, -Math.PI]}
                />
                <mesh
                  name="RCS_thruster_#1,_cone_#3"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#1,_cone_#3"].geometry}
                  material={nodes["RCS_thruster_#1,_cone_#3"].material}
                  position={[-0.41, 0, -0.13]}
                  rotation={[Math.PI / 2, 0, -Math.PI]}
                />
                <mesh
                  name="RCS_thruster_#1,_cone_#4"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#1,_cone_#4"].geometry}
                  material={nodes["RCS_thruster_#1,_cone_#4"].material}
                  position={[-0.41, 0, 0.12]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                />
                <mesh
                  name="RCS_thruster_#3,_cone_#4"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#3,_cone_#4"].geometry}
                  material={nodes["RCS_thruster_#3,_cone_#4"].material}
                  position={[0.41, 0, 0.13]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                />
                <mesh
                  name="RCS_thruster_#3,_cone_#3"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#3,_cone_#3"].geometry}
                  material={nodes["RCS_thruster_#3,_cone_#3"].material}
                  position={[0.41, 0, -0.13]}
                  rotation={[Math.PI / 2, 0, -Math.PI]}
                />
              </group>
              <group name="RCSthrusterbase2_4">
                <mesh
                  name="RCS_thruster_base_#2-4"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_base_#2-4"].geometry}
                  material={nodes["RCS_thruster_base_#2-4"].material}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  name="RCS_thruster_#2,_cone_#1"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#2,_cone_#1"].geometry}
                  material={nodes["RCS_thruster_#2,_cone_#1"].material}
                  position={[0, 0.13, -0.41]}
                />
                <mesh
                  name="RCS_thruster_#2,_cone_#2"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#2,_cone_#2"].geometry}
                  material={nodes["RCS_thruster_#2,_cone_#2"].material}
                  position={[0, -0.12, -0.41]}
                  rotation={[0, 0, -Math.PI]}
                />
                <mesh
                  name="RCS_thruster_#4,_cone_#1"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#4,_cone_#1"].geometry}
                  material={nodes["RCS_thruster_#4,_cone_#1"].material}
                  position={[0, 0.13, 0.41]}
                />
                <mesh
                  name="RCS_thruster_#4,_cone_#2"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#4,_cone_#2"].geometry}
                  material={nodes["RCS_thruster_#4,_cone_#2"].material}
                  position={[0, -0.12, 0.41]}
                  rotation={[0, 0, -Math.PI]}
                />
                <mesh
                  name="RCS_thruster_#2,_cone_#3"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#2,_cone_#3"].geometry}
                  material={nodes["RCS_thruster_#2,_cone_#3"].material}
                  position={[0.13, 0, -0.41]}
                  rotation={[0, 0, -Math.PI / 2]}
                />
                <mesh
                  name="RCS_thruster_#2,_cone_#4"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#2,_cone_#4"].geometry}
                  material={nodes["RCS_thruster_#2,_cone_#4"].material}
                  position={[-0.12, 0, -0.41]}
                  rotation={[0, 0, Math.PI / 2]}
                />
                <mesh
                  name="RCS_thruster_#4,_cone_#4"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#4,_cone_#4"].geometry}
                  material={nodes["RCS_thruster_#4,_cone_#4"].material}
                  position={[-0.12, 0, 0.41]}
                  rotation={[0, 0, Math.PI / 2]}
                />
                <mesh
                  name="RCS_thruster_#4,_cone_#3"
                  castShadow
                  receiveShadow
                  geometry={nodes["RCS_thruster_#4,_cone_#3"].geometry}
                  material={nodes["RCS_thruster_#4,_cone_#3"].material}
                  position={[0.13, 0, 0.41]}
                  rotation={[0, 0, -Math.PI / 2]}
                />
              </group>
              <mesh
                name="Tunnel_#2"
                castShadow
                receiveShadow
                geometry={nodes["Tunnel_#2"].geometry}
                material={nodes["Tunnel_#2"].material}
              />
            </group>
            <group name="Obervationmodule" position={[0, 1.12, 0]}>
              <group name="SPconnection" position={[-0.56, 0.28, 0]}>
                <group name="LeftSolarPannel" position={[-1.38, 0, 0]}>
                  <mesh
                    name="Solar_pannel_base"
                    castShadow
                    receiveShadow
                    geometry={nodes.Solar_pannel_base.geometry}
                    material={nodes.Solar_pannel_base.material}
                  />
                  <mesh
                    name="Solar_pannel_center_rod_#1"
                    castShadow
                    receiveShadow
                    geometry={nodes["Solar_pannel_center_rod_#1"].geometry}
                    material={nodes["Solar_pannel_center_rod_#1"].material}
                    position={[0.38, 0, -0.03]}
                  />
                  <mesh
                    name="Solar_pannel_center_rod_#2"
                    castShadow
                    receiveShadow
                    geometry={nodes["Solar_pannel_center_rod_#2"].geometry}
                    material={nodes["Solar_pannel_center_rod_#2"].material}
                    position={[-0.38, 0, -0.03]}
                  />
                </group>
                <group name="RightSolarPannel" position={[2.5, 0, -0.02]}>
                  <mesh
                    name="Solar_pannel_base_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Solar_pannel_base_1.geometry}
                    material={nodes.Solar_pannel_base_1.material}
                    position={[0, 0, 0.02]}
                  />
                  <mesh
                    name="Solar_pannel_center_rod_#1_1"
                    castShadow
                    receiveShadow
                    geometry={nodes["Solar_pannel_center_rod_#1_1"].geometry}
                    material={nodes["Solar_pannel_center_rod_#1_1"].material}
                    position={[0.38, 0, -0.01]}
                  />
                  <mesh
                    name="Solar_pannel_center_rod_#2_1"
                    castShadow
                    receiveShadow
                    geometry={nodes["Solar_pannel_center_rod_#2_1"].geometry}
                    material={nodes["Solar_pannel_center_rod_#2_1"].material}
                    position={[-0.38, 0, -0.01]}
                  />
                </group>
                <mesh
                  name="Solar_pannel_translator_#1"
                  castShadow
                  receiveShadow
                  geometry={nodes["Solar_pannel_translator_#1"].geometry}
                  material={nodes["Solar_pannel_translator_#1"].material}
                />
                <mesh
                  name="Solar_pannel_translator_#3"
                  castShadow
                  receiveShadow
                  geometry={nodes["Solar_pannel_translator_#3"].geometry}
                  material={nodes["Solar_pannel_translator_#3"].material}
                  position={[1.13, 0, 0]}
                />
                <mesh
                  name="SPT_holder_(1&3)"
                  castShadow
                  receiveShadow
                  geometry={nodes["SPT_holder_(1&3)"].geometry}
                  material={nodes["SPT_holder_(1&3)"].material}
                  position={[0.56, 0, 0]}
                />
                <mesh
                  name="Solar_pannel_translator_#2"
                  castShadow
                  receiveShadow
                  geometry={nodes["Solar_pannel_translator_#2"].geometry}
                  material={nodes["Solar_pannel_translator_#2"].material}
                  position={[0.56, 0, -0.56]}
                />
                <mesh
                  name="Solar_pannel_translator_#4"
                  castShadow
                  receiveShadow
                  geometry={nodes["Solar_pannel_translator_#4"].geometry}
                  material={nodes["Solar_pannel_translator_#4"].material}
                  position={[0.56, 0, 0.56]}
                />
                <mesh
                  name="SPT_holder_(2&4)"
                  castShadow
                  receiveShadow
                  geometry={nodes["SPT_holder_(2&4)"].geometry}
                  material={nodes["SPT_holder_(2&4)"].material}
                  position={[0.56, 0, 0]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  name="SP_link_#_1,_rod_#1"
                  castShadow
                  receiveShadow
                  geometry={nodes["SP_link_#_1,_rod_#1"].geometry}
                  material={nodes["SP_link_#_1,_rod_#1"].material}
                  position={[-0.19, 0, 0]}
                  rotation={[0, 0, Math.PI / 2]}
                />
                <mesh
                  name="SP_link_#3,_rod_#1"
                  castShadow
                  receiveShadow
                  geometry={nodes["SP_link_#3,_rod_#1"].geometry}
                  material={nodes["SP_link_#3,_rod_#1"].material}
                  position={[1.31, 0, 0]}
                  rotation={[0, 0, Math.PI / 2]}
                />
                <mesh
                  name="SPT_link_ring"
                  castShadow
                  receiveShadow
                  geometry={nodes.SPT_link_ring.geometry}
                  material={nodes.SPT_link_ring.material}
                  position={[0.56, 0, 0]}
                />
              </group>
              <mesh
                name="Observation_module"
                castShadow
                receiveShadow
                geometry={nodes.Observation_module.geometry}
                material={nodes.Observation_module.material}
              />
            </group>
            <group name="Servicemodule" position={[0, -1.09, 0]}>
              <group name="LQconnectionaxle" position={[0, 0.13, 0]}>
                <group name="RCS5" position={[-0.01, -0.01, -2.13]}>
                  <mesh
                    name="RCS_thruster_#5,_cone_#1"
                    castShadow
                    receiveShadow
                    geometry={nodes["RCS_thruster_#5,_cone_#1"].geometry}
                    material={nodes["RCS_thruster_#5,_cone_#1"].material}
                    position={[0, 0.12, -0.15]}
                    rotation={[0, Math.PI / 2, 0]}
                  />
                  <mesh
                    name="RCS_thruster_#5,_cone_#4"
                    castShadow
                    receiveShadow
                    geometry={nodes["RCS_thruster_#5,_cone_#4"].geometry}
                    material={nodes["RCS_thruster_#5,_cone_#4"].material}
                    position={[-0.12, 0, -0.15]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  />
                  <mesh
                    name="RCS_thruster_base_#5"
                    castShadow
                    receiveShadow
                    geometry={nodes["RCS_thruster_base_#5"].geometry}
                    material={nodes["RCS_thruster_base_#5"].material}
                    rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  />
                  <mesh
                    name="RCS_thruster_#5,_cone_#3"
                    castShadow
                    receiveShadow
                    geometry={nodes["RCS_thruster_#5,_cone_#3"].geometry}
                    material={nodes["RCS_thruster_#5,_cone_#3"].material}
                    position={[0.13, 0, -0.15]}
                    rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  />
                  <mesh
                    name="RCS_thruster_#5,_cone_#2"
                    castShadow
                    receiveShadow
                    geometry={nodes["RCS_thruster_#5,_cone_#2"].geometry}
                    material={nodes["RCS_thruster_#5,_cone_#2"].material}
                    position={[0, -0.13, -0.15]}
                    rotation={[-Math.PI, -Math.PI / 2, 0]}
                  />
                </group>
                <group name="RCS6" position={[0, -0.01, 2.25]}>
                  <mesh
                    name="RCS_thruster_base_#6"
                    castShadow
                    receiveShadow
                    geometry={nodes["RCS_thruster_base_#6"].geometry}
                    material={nodes["RCS_thruster_base_#6"].material}
                    position={[0, 0, -0.12]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  />
                  <mesh
                    name="RCS_thruster_#6,_cone_#1"
                    castShadow
                    receiveShadow
                    geometry={nodes["RCS_thruster_#6,_cone_#1"].geometry}
                    material={nodes["RCS_thruster_#6,_cone_#1"].material}
                    position={[0, 0.12, 0.03]}
                    rotation={[0, -Math.PI / 2, 0]}
                  />
                  <mesh
                    name="RCS_thruster_#6,_cone_#2"
                    castShadow
                    receiveShadow
                    geometry={nodes["RCS_thruster_#6,_cone_#2"].geometry}
                    material={nodes["RCS_thruster_#6,_cone_#2"].material}
                    position={[0, -0.13, 0.03]}
                    rotation={[Math.PI, Math.PI / 2, 0]}
                  />
                  <mesh
                    name="RCS_thruster_#6,_cone_#3"
                    castShadow
                    receiveShadow
                    geometry={nodes["RCS_thruster_#6,_cone_#3"].geometry}
                    material={nodes["RCS_thruster_#6,_cone_#3"].material}
                    position={[-0.13, 0, 0.03]}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  />
                  <mesh
                    name="RCS_thruster_#6,_cone_#4"
                    castShadow
                    receiveShadow
                    geometry={nodes["RCS_thruster_#6,_cone_#4"].geometry}
                    material={nodes["RCS_thruster_#6,_cone_#4"].material}
                    position={[0.12, 0, 0.03]}
                    rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  />
                </group>
                <mesh
                  name="LQ_connection_axle"
                  castShadow
                  receiveShadow
                  geometry={nodes.LQ_connection_axle.geometry}
                  material={nodes.LQ_connection_axle.material}
                />
                <mesh
                  name="LQ_connection_tunnel_#1-3"
                  castShadow
                  receiveShadow
                  geometry={nodes["LQ_connection_tunnel_#1-3"].geometry}
                  material={nodes["LQ_connection_tunnel_#1-3"].material}
                  rotation={[0, 0, Math.PI / 2]}
                />
                <mesh
                  name="Living_quarters"
                  castShadow
                  receiveShadow
                  geometry={nodes.Living_quarters.geometry}
                  material={nodes.Living_quarters.material}
                />
                <mesh
                  name="LQ_connection_tunnel_#2-4"
                  castShadow
                  receiveShadow
                  geometry={nodes["LQ_connection_tunnel_#2-4"].geometry}
                  material={nodes["LQ_connection_tunnel_#2-4"].material}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                />
              </group>
              <group name="NozzleExtension" position={[0, -1.21, 0]}>
                <mesh
                  name="Nozzle_Extension"
                  castShadow
                  receiveShadow
                  geometry={nodes.Nozzle_Extension.geometry}
                  material={nodes.Nozzle_Extension.material}
                  position={[0, 0.01, 0]}
                />
                <mesh
                  name="NE_Ring1"
                  castShadow
                  receiveShadow
                  geometry={nodes.NE_Ring1.geometry}
                  material={nodes.NE_Ring1.material}
                  position={[0, -0.15, 0]}
                />
                <mesh
                  name="NE_Ring2"
                  castShadow
                  receiveShadow
                  geometry={nodes.NE_Ring2.geometry}
                  material={nodes.NE_Ring2.material}
                  position={[0, 0.13, 0]}
                />
              </group>
              <mesh
                name="Service_module"
                castShadow
                receiveShadow
                geometry={nodes.Service_module.geometry}
                material={nodes.Service_module.material}
              />
            </group>
            <mesh
              name="Tunnel_#1"
              castShadow
              receiveShadow
              geometry={nodes["Tunnel_#1"].geometry}
              material={nodes["Tunnel_#1"].material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model.gltf");
